from __future__ import annotations

from typing import Any

from app.models import EvidenceRecord


SHLIB_HISTORY_URL = "https://www.library.sh.cn/resource?type=%E5%8E%86%E5%8F%B2%E6%96%87%E7%8C%AE%E8%B5%84%E6%BA%90"
SHLIB_BOOK_URL = "https://www.library.sh.cn/resource?type=%E5%9B%BE%E4%B9%A6"
SHLIB_DIGITAL_URL = "https://www.library.sh.cn/resource?type=%E6%95%B0%E5%AD%97%E8%B5%84%E6%BA%90"


def seed_record(
    *,
    record_id: str,
    title: str,
    snippet: str,
    dataset: str,
    date: str = "",
    persons: list[str] | None = None,
    places: list[str] | None = None,
    topics: list[str] | None = None,
    source_uri: str = SHLIB_HISTORY_URL,
    evidence_type: str = "curated_demo_seed",
    public_tags: list[str] | None = None,
    verification_notes: list[str] | None = None,
    geo: dict[str, Any] | None = None,
) -> EvidenceRecord:
    tags = public_tags or ["library_open_data"]
    notes = verification_notes or [
        "Demo seed record only; replace with live Shanghai Library API evidence before use.",
        "Open the local source page and verify the intended dataset family, title, period, and claim strength.",
    ]
    return EvidenceRecord(
        record_id=record_id,
        title=title,
        snippet=snippet,
        source="ContextLens transparent demo seed for Shanghai Library ODC",
        source_uri=source_uri,
        dataset=dataset,
        date=date,
        persons=persons or [],
        places=places or [],
        topics=topics or [],
        raw={
            "demo_seed": True,
            "intended_use": "Fallback evidence for local prototype and public demo flow.",
            "target_live_sources": [
                "Shanghai Library Open Data API",
                "Shanghai Library authority/entity data",
                "Shanghai gazetteer, road, event, bibliographic, periodical, or archival datasets where applicable.",
            ],
            "public_tags": tags,
        },
        is_live_api=False,
        evidence_type=evidence_type,
        provenance_note=(
            "Transparent curated fallback record. It sketches the intended evidence shape and must be replaced or "
            "confirmed with live Shanghai Library records before use."
        ),
        time_span=date,
        geo=geo or {},
        public_tags=tags,
        verification_notes=notes,
    )


SAMPLE_RECORDS: list[EvidenceRecord] = [
    seed_record(
        record_id="demo-silver-customs-001",
        title="银两、海关与近代跨境贸易",
        snippet="晚清至民国时期，海关、银两核算、关税征收和口岸贸易共同构成跨境交易的制度基础。该类材料适合解释货币计价、信用、税则与国际贸易秩序之间的关系。",
        dataset="demo_seed:customs_money_trade",
        date="晚清/近代",
        places=["上海", "通商口岸"],
        topics=["银", "海关", "关税", "跨境贸易", "货币", "制度"],
        evidence_type="thematic_context_seed",
        public_tags=["shanghai_world", "institutional_history"],
    ),
    seed_record(
        record_id="demo-sheng-archive-002",
        title="盛宣怀档案与近代金融、铁路、招商和外交事务",
        snippet="盛宣怀相关档案常涉及轮船招商、铁路、电报、银行、矿务和对外事务，是理解近代中国基础设施、金融制度与国际贸易关系的重要线索。",
        dataset="demo_seed:sheng_archive",
        date="晚清",
        persons=["盛宣怀"],
        places=["上海", "江南"],
        topics=["盛宣怀", "银行", "招商", "铁路", "外交", "基础设施", "轮船招商局"],
        evidence_type="archive_context_seed",
        public_tags=["trace_person", "shanghai_world", "industrial_heritage"],
    ),
    seed_record(
        record_id="demo-paper-money-003",
        title="纸币、交子与稳定价值结算的历史问题",
        snippet="中国历史上的纸币实践体现了国家信用、发行约束、通货稳定和交易便利之间的张力，可作为讨论稳定价值数字结算时的历史参照。",
        dataset="demo_seed:monetary_history",
        date="宋元明清",
        topics=["纸币", "交子", "会子", "信用", "稳定价值结算", "货币制度"],
        source_uri=SHLIB_BOOK_URL,
        evidence_type="bibliographic_context_seed",
        public_tags=["shanghai_world", "institutional_history"],
    ),
    seed_record(
        record_id="demo-silk-road-004",
        title="丝绸之路贸易中的路线、使节与商人网络",
        snippet="丝绸之路连接商品、人员、信息和外交关系。路线安全、使节制度、商人网络与多币种交易共同影响跨区域贸易的可持续性。",
        dataset="demo_seed:silk_road",
        date="汉唐以后",
        persons=["张骞"],
        places=["西域", "中亚"],
        topics=["丝绸之路", "商路", "使节", "外交", "商人网络", "信任"],
        evidence_type="route_context_seed",
        public_tags=["shanghai_world", "public_story"],
    ),
    seed_record(
        record_id="demo-maritime-trade-005",
        title="海上丝路、港口与跨区域贸易秩序",
        snippet="海上贸易依赖港口、航线、关税、商人组织和外交秩序。港口制度与通关机制可用于解释现代港口和供应链治理问题。",
        dataset="demo_seed:maritime_routes",
        date="宋元明清",
        places=["泉州", "广州", "上海"],
        topics=["海上丝路", "港口", "口岸", "供应链", "国际贸易", "航线"],
        evidence_type="route_context_seed",
        public_tags=["shanghai_world", "city_walk"],
    ),
    seed_record(
        record_id="demo-treaty-port-006",
        title="通商口岸、银行与国际结算机制",
        snippet="近代通商口岸集中了海关、银行、商行、保险、航运和外贸制度，是观察跨境结算、信用中介和国际规则进入本土市场的重要场景。",
        dataset="demo_seed:treaty_ports",
        date="近代",
        places=["上海", "天津", "广州"],
        topics=["通商口岸", "银行", "结算", "信用", "外贸", "保险", "航运"],
        source_uri=SHLIB_BOOK_URL,
        evidence_type="thematic_context_seed",
        public_tags=["shanghai_world", "institutional_history"],
    ),
    seed_record(
        record_id="demo-tea-horse-007",
        title="茶马互市与边疆贸易制度",
        snippet="茶马互市体现了边疆贸易、国家治理、商品交换和外交关系的结合，适合说明贸易并非单纯市场行为，而常与政策和边疆秩序相连。",
        dataset="demo_seed:frontier_trade",
        date="唐宋明清",
        places=["西南", "西北"],
        topics=["茶马互市", "边疆贸易", "外交", "治理", "商品交换"],
        evidence_type="event_context_seed",
        public_tags=["public_story", "institutional_history"],
    ),
    seed_record(
        record_id="demo-merchant-network-008",
        title="商帮、票号与跨区域信用网络",
        snippet="商帮和票号通过声誉、契约、汇兑和跨地网络降低交易成本，为理解现代跨境价值转移和信用基础设施提供历史类比。",
        dataset="demo_seed:merchant_credit",
        date="明清",
        places=["山西", "上海"],
        topics=["商帮", "票号", "汇兑", "信用", "跨区域贸易", "契约"],
        evidence_type="network_context_seed",
        public_tags=["shanghai_world", "family_memory"],
    ),
    seed_record(
        record_id="demo-lu-xun-shanghai-009",
        title="鲁迅在上海的出版、交往与公共文化线索",
        snippet="鲁迅寓居上海期间，与书店、刊物、青年作者、公共文化空间和近代出版网络密切相关。该类材料适合从人物线索重建地点、文献与机构关系。",
        dataset="demo_seed:public_culture_people",
        date="民国",
        persons=["鲁迅", "许广平"],
        places=["上海", "虹口"],
        topics=["人物传记", "出版", "书店", "刊物", "公共文化", "左翼文化"],
        evidence_type="person_document_context_seed",
        public_tags=["trace_person", "public_culture", "city_walk"],
    ),
    seed_record(
        record_id="demo-bund-place-010",
        title="外滩历史建筑、口岸机构与近代上海空间变迁",
        snippet="外滩及周边历史建筑常与银行、海关、商行、航运公司和租界治理相连，是从一处旧址追踪机构、人物和贸易事件的典型入口。",
        dataset="demo_seed:historic_buildings",
        date="近代",
        places=["外滩", "上海"],
        topics=["历史建筑", "地名", "海关", "银行", "商行", "航运", "租界"],
        evidence_type="place_context_seed",
        public_tags=["city_walk", "explore_place", "shanghai_world"],
        geo={"status": "needs_geocoding", "place_candidates": ["外滩"]},
    ),
    seed_record(
        record_id="demo-shanghai-event-011",
        title="近代上海通商事件的时间线、参与者与制度影响",
        snippet="通商口岸相关事件可连接海关制度、商人组织、外贸规则、城市空间和金融中介，适合还原事件过程并检查因果解释是否有证据支撑。",
        dataset="demo_seed:shanghai_events",
        date="晚清/民国",
        places=["上海", "通商口岸"],
        topics=["历史事件", "时间线", "海关", "商人", "外贸", "城市空间"],
        evidence_type="event_context_seed",
        public_tags=["reconstruct_event", "shanghai_world"],
    ),
    seed_record(
        record_id="demo-document-reading-012",
        title="近代报刊索引与档案题名的文献解读路径",
        snippet="报刊索引、档案题名和书目记录通常提供题名、年代、责任者、馆藏类型和主题词，可作为读懂一份历史文献并追溯相关人物地点的入口。",
        dataset="demo_seed:document_reading",
        date="近代",
        places=["上海"],
        topics=["文献", "档案", "报刊索引", "书目", "题名", "出处", "责任者"],
        source_uri=SHLIB_DIGITAL_URL,
        evidence_type="document_context_seed",
        public_tags=["document_detective", "read_document"],
    ),
    seed_record(
        record_id="demo-zhang-qian-reception-013",
        title="张骞形象在后世文献与丝路叙事中的流动",
        snippet="张骞作为人物线索，常被后世文献、通道叙事和丝绸之路研究重新引用。该类材料适合区分历史人物、后世解释和公共叙事之间的证据边界。",
        dataset="demo_seed:historical_reception",
        date="汉代/后世文献",
        persons=["张骞"],
        places=["西域", "中亚"],
        topics=["张骞", "后世文献", "丝绸之路", "人物传记", "公共叙事", "外交"],
        evidence_type="person_reception_seed",
        public_tags=["trace_person", "public_story"],
    ),
    seed_record(
        record_id="demo-remittance-note-014",
        title="晚清汇票、商人、银行、口岸与海外贸易网络",
        snippet="晚清汇票和汇兑材料可把商人、票号、银行、口岸、航运和海外贸易联系起来，用于追踪一张金融文书背后的跨地域信用网络。",
        dataset="demo_seed:remittance_document",
        date="晚清",
        places=["上海", "通商口岸"],
        topics=["汇票", "汇兑", "票号", "商人", "银行", "口岸", "航运", "海外贸易"],
        source_uri=SHLIB_DIGITAL_URL,
        evidence_type="document_context_seed",
        public_tags=["document_detective", "shanghai_world"],
    ),
    seed_record(
        record_id="demo-old-address-neighborhood-015",
        title="旧地址、地名变迁与近代上海邻近历史事件",
        snippet="旧地址研究通常需要把门牌、道路、里弄、历史建筑、机构占用和邻近事件放在一起复核，再通过地名志或历史地图确认现代位置。",
        dataset="demo_seed:old_address",
        date="近代/民国",
        places=["上海", "旧地址", "道路", "里弄"],
        topics=["旧地址", "地名", "道路", "历史建筑", "历史事件", "空间轨迹", "机构"],
        evidence_type="place_context_seed",
        public_tags=["city_walk", "family_memory", "explore_place"],
        geo={"status": "needs_geocoding", "place_candidates": ["旧地址", "里弄"]},
    ),
    seed_record(
        record_id="demo-nanjing-road-016",
        title="南京路商业文化、报刊广告与近代市民生活",
        snippet="南京路作为商业街区线索，可连接百货公司、报刊广告、消费文化、交通节点和市民日常。适合把上海图书馆数据转化为公众可走、可看的城市记忆路线。",
        dataset="demo_seed:urban_commerce",
        date="民国/近代",
        places=["南京路", "上海"],
        topics=["商业文化", "报刊广告", "百货公司", "市民生活", "交通", "城市漫游"],
        evidence_type="place_periodical_context_seed",
        public_tags=["city_walk", "public_culture"],
        geo={"status": "needs_geocoding", "place_candidates": ["南京路"]},
    ),
    seed_record(
        record_id="demo-shikumen-lilong-017",
        title="石库门、里弄与社区生活记忆",
        snippet="石库门和里弄材料可把建筑形态、居民组织、商业服务、道路名称和社区事件联系起来，适合作为普通市民从旧住址进入历史调查的入口。",
        dataset="demo_seed:neighborhood_memory",
        date="近代/民国",
        places=["上海", "石库门", "里弄"],
        topics=["石库门", "里弄", "社区生活", "旧地址", "城市记忆", "建筑"],
        evidence_type="neighborhood_context_seed",
        public_tags=["city_walk", "family_memory", "public_story"],
        geo={"status": "needs_geocoding", "place_candidates": ["石库门", "里弄"]},
    ),
    seed_record(
        record_id="demo-family-genealogy-018",
        title="家谱、人名规范与旧籍中的个人线索",
        snippet="家谱、人物传记资料和书目记录可以帮助公众从姓氏、祖籍、旧居或亲属姓名出发，建立可复核的人物关系和文献追踪路线。",
        dataset="demo_seed:genealogy_people",
        date="明清/近代",
        topics=["家谱", "人名规范", "族谱", "祖籍", "人物关系", "旧籍", "寻亲"],
        source_uri=SHLIB_BOOK_URL,
        evidence_type="genealogy_context_seed",
        public_tags=["family_memory", "trace_person", "document_detective"],
    ),
    seed_record(
        record_id="demo-song-ching-ling-019",
        title="宋庆龄在上海的寓所、公益机构与国际联系",
        snippet="宋庆龄相关线索可把人物、寓所、公益组织、国际交往和近现代公共记忆联系起来，适合展示人物调查如何面向公众叙事又保持证据边界。",
        dataset="demo_seed:public_figures",
        date="民国/近现代",
        persons=["宋庆龄"],
        places=["上海"],
        topics=["寓所", "公益机构", "国际联系", "人物传记", "公共记忆"],
        evidence_type="person_place_context_seed",
        public_tags=["trace_person", "city_walk", "public_culture"],
    ),
    seed_record(
        record_id="demo-zhang-ailing-020",
        title="张爱玲与上海城市文学地景",
        snippet="张爱玲相关文献和城市地点可连接作家、作品、出版机构、公寓、道路和读者记忆，是公众兴趣较强的文学地景调查入口。",
        dataset="demo_seed:literary_shanghai",
        date="民国",
        persons=["张爱玲"],
        places=["上海"],
        topics=["文学地景", "作家", "作品", "公寓", "出版", "城市记忆"],
        source_uri=SHLIB_BOOK_URL,
        evidence_type="literary_context_seed",
        public_tags=["trace_person", "city_walk", "public_culture"],
    ),
    seed_record(
        record_id="demo-shanghai-film-021",
        title="上海电影、影院空间与近代公共娱乐",
        snippet="电影公司、影院、报刊影评和明星资料可把地点、人物、机构和公共娱乐联系起来，适合把历史数据做成公众可探索的文化网络。",
        dataset="demo_seed:film_culture",
        date="民国",
        places=["上海"],
        topics=["电影", "影院", "明星", "影评", "公共娱乐", "报刊"],
        evidence_type="periodical_culture_seed",
        public_tags=["public_culture", "city_walk", "reconstruct_event"],
    ),
    seed_record(
        record_id="demo-old-map-photo-022",
        title="老地图、老照片与历史地名交叉考证",
        snippet="老地图、照片说明、道路数据和地名志可以相互校验旧地址和现代位置。该类材料适合支持空间证据层，但需要明确坐标复核状态。",
        dataset="demo_seed:map_photo_gazetteer",
        date="近代/民国",
        places=["上海", "道路", "旧址"],
        topics=["老地图", "老照片", "历史地名", "地名志", "空间考证", "坐标复核"],
        source_uri=SHLIB_DIGITAL_URL,
        evidence_type="visual_or_map_context_seed",
        public_tags=["city_walk", "explore_place", "document_detective"],
        geo={"status": "needs_geocoding", "place_candidates": ["道路", "旧址"]},
    ),
    seed_record(
        record_id="demo-rare-book-seal-023",
        title="古籍题跋、藏书印与文献流转线索",
        snippet="古籍题跋、藏书印和版本记录可揭示一本文献的收藏、刊刻、流传和阅读关系，适合把“读懂一份文献”做成文献侦探体验。",
        dataset="demo_seed:rare_books",
        date="明清/民国",
        topics=["古籍", "题跋", "藏书印", "版本", "文献流转", "收藏"],
        source_uri=SHLIB_BOOK_URL,
        evidence_type="rare_book_context_seed",
        public_tags=["document_detective", "read_document"],
    ),
    seed_record(
        record_id="demo-newspaper-rumor-024",
        title="近代报刊中的事件传闻、澄清与公共舆论",
        snippet="报刊材料常同时包含事件报道、传闻、广告和评论。ContextLens 应把报道事实、舆论表达和后续澄清分开，避免把单一报刊语句直接当作确定事实。",
        dataset="demo_seed:periodical_event_audit",
        date="近代/民国",
        places=["上海"],
        topics=["报刊", "事件", "传闻", "澄清", "公共舆论", "反证"],
        source_uri=SHLIB_DIGITAL_URL,
        evidence_type="periodical_context_seed",
        public_tags=["reconstruct_event", "document_detective", "guardrails"],
    ),
    seed_record(
        record_id="demo-school-alumni-025",
        title="校友名录、学校旧址与人物流动",
        snippet="校友录和学校旧址材料可把普通人物、教育机构、迁徙路径和城市空间联系起来，是面向公众的低门槛个人历史调查入口。",
        dataset="demo_seed:education_memory",
        date="近代/民国",
        places=["上海"],
        topics=["校友录", "学校旧址", "教育机构", "人物流动", "旧地址"],
        source_uri=SHLIB_BOOK_URL,
        evidence_type="institution_people_context_seed",
        public_tags=["family_memory", "trace_person", "city_walk"],
    ),
    seed_record(
        record_id="demo-industrial-heritage-026",
        title="杨树浦工业遗产、工厂机构与滨江空间变迁",
        snippet="杨树浦等工业区域线索可连接工厂、公司、工人、码头、铁路和滨江空间更新，适合展示历史证据如何服务城市记忆与公共教育。",
        dataset="demo_seed:industrial_heritage",
        date="近代/民国",
        places=["杨树浦", "上海", "滨江"],
        topics=["工业遗产", "工厂", "码头", "铁路", "工人", "城市更新"],
        evidence_type="place_industry_context_seed",
        public_tags=["city_walk", "industrial_heritage", "public_story"],
        geo={"status": "needs_geocoding", "place_candidates": ["杨树浦", "滨江"]},
    ),
    seed_record(
        record_id="demo-refugee-memory-027",
        title="提篮桥、难民记忆与上海国际城市经验",
        snippet="提篮桥等地点可连接战时难民、社区机构、宗教文化、国际救援和城市公共记忆。该类主题公众关注度高，但需要谨慎区分个体记忆、机构记录和后世纪念。",
        dataset="demo_seed:international_memory",
        date="民国/战时",
        places=["提篮桥", "上海"],
        topics=["难民记忆", "国际救援", "社区机构", "宗教文化", "公共记忆", "战时"],
        evidence_type="memory_place_context_seed",
        public_tags=["city_walk", "public_culture", "guardrails"],
        geo={"status": "needs_geocoding", "place_candidates": ["提篮桥"]},
    ),
    seed_record(
        record_id="demo-women-public-life-028",
        title="近代上海女性公共生活、职业教育与报刊呈现",
        snippet="女性职业教育、报刊报道、社团活动和公共空间材料可支持更广泛的公众历史议题，帮助避免项目只围绕商业或宏观制度展开。",
        dataset="demo_seed:gender_public_life",
        date="近代/民国",
        places=["上海"],
        topics=["女性", "职业教育", "社团", "报刊", "公共空间", "社会史"],
        source_uri=SHLIB_DIGITAL_URL,
        evidence_type="social_history_context_seed",
        public_tags=["public_culture", "reconstruct_event", "document_detective"],
    ),
    seed_record(
        record_id="demo-waterfront-shipping-029",
        title="黄浦江码头、航运机构与城市物流网络",
        snippet="黄浦江码头和航运机构线索可把水岸空间、公司、货物流、口岸制度和城市基础设施连成一张可视化调查网络。",
        dataset="demo_seed:waterfront_shipping",
        date="近代",
        places=["黄浦江", "上海", "码头"],
        topics=["航运", "码头", "物流", "口岸", "基础设施", "城市空间"],
        evidence_type="place_network_context_seed",
        public_tags=["city_walk", "shanghai_world", "industrial_heritage"],
        geo={"status": "needs_geocoding", "place_candidates": ["黄浦江", "码头"]},
    ),
    seed_record(
        record_id="demo-community-exhibit-030",
        title="从个人线索到社区展陈的历史档案生成路径",
        snippet="一个姓名、旧地址或文献题名可以被转化为社区展陈小档案：先确认实体，再形成证据卡、时间线、关系图、故事文本和未证实边界。",
        dataset="demo_seed:public_dossier_method",
        date="方法型记录",
        topics=["社区展陈", "个人线索", "证据卡", "时间线", "关系图", "故事模式", "研究模式"],
        evidence_type="method_context_seed",
        public_tags=["family_memory", "city_walk", "public_story", "award_readiness"],
    ),
]


SAMPLE_RECORDS.extend(
    [
        seed_record(
            record_id="demo-transport-tram-031",
            title="有轨电车、公共汽车与近代上海日常出行",
            snippet="交通线路、站点、票价、报刊广告和道路变迁可把普通市民的上学、上班、购物和观影路线串成可复核的城市生活时间线。",
            dataset="demo_seed:urban_transport",
            date="民国/近代",
            places=["上海", "南京路", "公共租界"],
            topics=["有轨电车", "公共汽车", "交通", "站点", "报刊广告", "城市生活"],
            evidence_type="transport_context_seed",
            public_tags=["city_walk", "public_culture", "urban_daily_life"],
            geo={"status": "needs_geocoding", "place_candidates": ["南京路", "公共租界"]},
        ),
        seed_record(
            record_id="demo-library-reading-room-032",
            title="图书馆阅览室、读者记录与公共知识空间",
            snippet="阅览室、读者服务、目录卡片和借阅制度体现上海公共知识空间的形成，可用于展示上海图书馆数据如何反哺公众文化记忆。",
            dataset="demo_seed:library_public_space",
            date="近代/民国",
            places=["上海"],
            topics=["图书馆", "阅览室", "读者", "目录", "公共知识", "文化空间"],
            source_uri=SHLIB_DIGITAL_URL,
            evidence_type="library_history_context_seed",
            public_tags=["public_culture", "document_detective", "award_readiness"],
        ),
        seed_record(
            record_id="demo-park-public-life-033",
            title="公园、游园会与城市公共生活",
            snippet="公园开放、游园会、社团活动和报刊报道可连接公共空间、社会组织和市民休闲，是普通用户容易理解的上海城市记忆入口。",
            dataset="demo_seed:parks_public_life",
            date="近代/民国",
            places=["上海", "公园"],
            topics=["公园", "游园会", "社团", "公共空间", "市民休闲", "报刊"],
            evidence_type="public_space_context_seed",
            public_tags=["city_walk", "public_culture", "social_history"],
            geo={"status": "needs_geocoding", "place_candidates": ["公园"]},
        ),
        seed_record(
            record_id="demo-hospital-charity-034",
            title="医院、慈善机构与城市救助网络",
            snippet="医院、慈善组织、募捐广告和报刊报道可把个人故事、机构档案和城市公共服务联系起来，适合做社会史和公众教育场景。",
            dataset="demo_seed:health_charity",
            date="近代/民国",
            places=["上海"],
            topics=["医院", "慈善", "募捐", "公共卫生", "机构", "报刊"],
            evidence_type="institution_social_context_seed",
            public_tags=["public_culture", "reconstruct_event", "social_history"],
        ),
        seed_record(
            record_id="demo-museum-exhibition-035",
            title="博物馆、展览会与公众教育",
            snippet="展览会目录、讲座启事、馆藏说明和报刊评论可揭示知识如何被组织成公共展陈，适合为 ContextLens 生成社区展板或讲解词。",
            dataset="demo_seed:museum_exhibition",
            date="近代/民国",
            places=["上海"],
            topics=["博物馆", "展览会", "讲座", "馆藏", "公众教育", "报刊评论"],
            source_uri=SHLIB_DIGITAL_URL,
            evidence_type="exhibition_context_seed",
            public_tags=["public_story", "document_detective", "award_readiness"],
        ),
        seed_record(
            record_id="demo-labor-union-036",
            title="工会、工厂报刊与劳动者城市经验",
            snippet="工会、工厂、报刊报道和城市空间可以帮助还原劳动者的组织活动、迁徙路径和公共诉求，但事件因果需要多来源复核。",
            dataset="demo_seed:labor_history",
            date="近代/民国",
            places=["上海", "杨树浦"],
            topics=["工会", "工厂", "工人", "报刊", "城市经验", "社会运动"],
            evidence_type="labor_event_context_seed",
            public_tags=["industrial_heritage", "reconstruct_event", "guardrails"],
            geo={"status": "needs_geocoding", "place_candidates": ["杨树浦"]},
        ),
        seed_record(
            record_id="demo-port-ticket-037",
            title="船票、码头广告与跨城流动",
            snippet="船票、航线广告、码头机构和旅客指南可把个人移动、城市交通和上海口岸网络联系起来，适合作为家族迁徙和城市流动调查入口。",
            dataset="demo_seed:mobility_documents",
            date="近代/民国",
            places=["上海", "黄浦江", "码头"],
            topics=["船票", "航线", "码头", "旅客指南", "迁徙", "口岸"],
            evidence_type="mobility_document_seed",
            public_tags=["family_memory", "city_walk", "shanghai_world"],
            geo={"status": "needs_geocoding", "place_candidates": ["码头", "黄浦江"]},
        ),
        seed_record(
            record_id="demo-railway-timetable-038",
            title="铁路时刻表、车站与近代出行网络",
            snippet="铁路时刻表、车站名、票价和新闻报道能把城市和区域交通连成时间线，也能帮助用户理解人物为何在某些地点之间移动。",
            dataset="demo_seed:railway_mobility",
            date="晚清/民国",
            places=["上海", "江南"],
            topics=["铁路", "时刻表", "车站", "票价", "区域交通", "人物流动"],
            evidence_type="timetable_context_seed",
            public_tags=["family_memory", "city_walk", "industrial_heritage"],
        ),
        seed_record(
            record_id="demo-store-receipt-039",
            title="百货公司收据、广告与消费文化",
            snippet="收据、商品广告、橱窗报道和报刊副刊可用于解释南京路商业文化如何进入市民日常，并形成可视化消费史证据链。",
            dataset="demo_seed:consumer_documents",
            date="民国",
            places=["南京路", "上海"],
            topics=["百货公司", "收据", "广告", "橱窗", "消费文化", "报刊副刊"],
            evidence_type="commerce_document_seed",
            public_tags=["city_walk", "public_culture", "document_detective"],
            geo={"status": "needs_geocoding", "place_candidates": ["南京路"]},
        ),
        seed_record(
            record_id="demo-school-yearbook-040",
            title="学校年刊、毕业合影与校友网络",
            snippet="学校年刊、毕业合影、校友录和校址变迁可把普通人物、教育机构和城市地点连接起来，是家族线索寻踪中非常有用的证据类型。",
            dataset="demo_seed:school_yearbooks",
            date="民国/近代",
            places=["上海"],
            topics=["学校年刊", "毕业合影", "校友录", "校址", "教育机构", "人物关系"],
            source_uri=SHLIB_BOOK_URL,
            evidence_type="education_document_seed",
            public_tags=["family_memory", "trace_person", "document_detective"],
        ),
        seed_record(
            record_id="demo-photo-studio-041",
            title="照相馆、人物肖像与城市商业空间",
            snippet="照相馆地址、肖像背印、广告和人物资料可以把一张家庭老照片转化为地点、机构和人物关系调查，但身份判断必须保留不确定性。",
            dataset="demo_seed:photo_studios",
            date="近代/民国",
            places=["上海", "南京路"],
            topics=["照相馆", "老照片", "肖像", "背印", "广告", "身份消歧"],
            evidence_type="photo_provenance_seed",
            public_tags=["family_memory", "city_walk", "document_detective"],
            geo={"status": "needs_geocoding", "place_candidates": ["南京路"]},
        ),
        seed_record(
            record_id="demo-shop-directory-042",
            title="商号名录、电话簿与机构地址复核",
            snippet="商号名录和电话簿可用于确认机构名称、地址、行业分类和迁址情况，适合支撑旧地址、公司、店铺和个人职业线索。",
            dataset="demo_seed:directories",
            date="民国",
            places=["上海"],
            topics=["商号名录", "电话簿", "机构地址", "行业分类", "迁址", "旧地址"],
            source_uri=SHLIB_DIGITAL_URL,
            evidence_type="directory_context_seed",
            public_tags=["city_walk", "family_memory", "source_verification"],
        ),
        seed_record(
            record_id="demo-theater-program-043",
            title="剧院戏单、演出广告与文化夜生活",
            snippet="戏单、剧院广告、演员名录和报刊评论可把剧场空间、人物、作品和夜生活联系起来，适合公共文化和城市漫游场景。",
            dataset="demo_seed:theater_culture",
            date="民国",
            places=["上海"],
            topics=["剧院", "戏单", "演出广告", "演员", "夜生活", "报刊评论"],
            evidence_type="performance_document_seed",
            public_tags=["public_culture", "city_walk", "document_detective"],
        ),
        seed_record(
            record_id="demo-temple-festival-044",
            title="庙会、地方信仰与社区商业网络",
            snippet="庙会启事、地方志、商铺广告和交通线索可把社区生活、商业网络和节庆时间联系起来，是公众容易产生兴趣的社会史入口。",
            dataset="demo_seed:community_festivals",
            date="明清/近代",
            places=["上海", "老城厢"],
            topics=["庙会", "地方信仰", "社区商业", "节庆", "地方志", "交通"],
            evidence_type="festival_context_seed",
            public_tags=["city_walk", "public_story", "social_history"],
            geo={"status": "needs_geocoding", "place_candidates": ["老城厢"]},
        ),
        seed_record(
            record_id="demo-oral-history-index-045",
            title="口述史索引、个人记忆与证据边界",
            snippet="口述史索引可以提供个人记忆、地点称呼和事件线索，但必须和档案、报刊、地名志等来源互证，避免把记忆直接写成事实。",
            dataset="demo_seed:oral_history",
            date="近现代",
            places=["上海"],
            topics=["口述史", "个人记忆", "证据边界", "互证", "地点称呼", "事件线索"],
            source_uri=SHLIB_DIGITAL_URL,
            evidence_type="oral_history_context_seed",
            public_tags=["family_memory", "public_story", "guardrails"],
        ),
        seed_record(
            record_id="demo-address-change-register-046",
            title="门牌变更、道路改名与地址消歧",
            snippet="门牌变更和道路改名记录能帮助把旧地址对应到现代空间，是城市记忆和家族寻踪最关键的基础数据之一。",
            dataset="demo_seed:address_disambiguation",
            date="近代/现代",
            places=["上海", "道路", "旧地址"],
            topics=["门牌", "道路改名", "地址消歧", "地名志", "现代坐标", "旧居"],
            evidence_type="address_authority_seed",
            public_tags=["city_walk", "family_memory", "source_verification"],
            geo={"status": "needs_geocoding", "place_candidates": ["旧地址", "道路"]},
        ),
        seed_record(
            record_id="demo-calendar-almanac-047",
            title="月份牌、年历广告与视觉文化",
            snippet="月份牌和年历广告可连接商业品牌、女性形象、印刷机构和城市消费场景，是从图像进入近代上海公共文化的线索。",
            dataset="demo_seed:visual_culture",
            date="民国",
            places=["上海"],
            topics=["月份牌", "年历广告", "视觉文化", "女性形象", "印刷", "消费场景"],
            source_uri=SHLIB_DIGITAL_URL,
            evidence_type="visual_culture_seed",
            public_tags=["public_culture", "document_detective", "city_walk"],
        ),
        seed_record(
            record_id="demo-bookstore-network-048",
            title="书店、出版发行与读者社群",
            snippet="书店地址、出版发行记录、广告和作者往来可把文献题名、人物关系和城市文化空间连接起来，适合鲁迅、张爱玲等人物调查。",
            dataset="demo_seed:bookstore_networks",
            date="民国",
            persons=["鲁迅", "张爱玲"],
            places=["上海"],
            topics=["书店", "出版发行", "读者社群", "作者往来", "文献题名", "广告"],
            source_uri=SHLIB_BOOK_URL,
            evidence_type="publishing_network_seed",
            public_tags=["trace_person", "public_culture", "document_detective"],
        ),
        seed_record(
            record_id="demo-newspaper-ad-index-049",
            title="报刊广告索引、商号与城市消费地图",
            snippet="报刊广告索引可将商号、商品、地址、日期和读者对象组合起来，支持从单条广告追踪城市商业网络。",
            dataset="demo_seed:newspaper_ads",
            date="民国",
            places=["上海", "南京路"],
            topics=["报刊广告", "商号", "商品", "地址", "消费地图", "读者"],
            source_uri=SHLIB_DIGITAL_URL,
            evidence_type="periodical_ad_seed",
            public_tags=["city_walk", "document_detective", "public_culture"],
            geo={"status": "needs_geocoding", "place_candidates": ["南京路"]},
        ),
        seed_record(
            record_id="demo-police-permit-050",
            title="许可、登记与城市治理记录",
            snippet="许可和登记材料可揭示机构、活动、地址和时间，但涉及个人或敏感社会事件时应只做公共知识解释，避免过度推断。",
            dataset="demo_seed:urban_governance",
            date="近代/民国",
            places=["上海"],
            topics=["许可", "登记", "城市治理", "机构", "活动", "证据边界"],
            evidence_type="governance_record_seed",
            public_tags=["reconstruct_event", "guardrails", "source_verification"],
        ),
        seed_record(
            record_id="demo-ferry-bridge-051",
            title="渡口、桥梁与滨水生活路线",
            snippet="渡口、桥梁、码头和河岸市场材料可把黄浦江两岸生活、工业区和交通网络连成公众可走读的滨水历史路线。",
            dataset="demo_seed:waterfront_mobility",
            date="近代/民国",
            places=["黄浦江", "上海", "渡口", "桥梁"],
            topics=["渡口", "桥梁", "码头", "滨水生活", "交通网络", "工业区"],
            evidence_type="waterfront_place_seed",
            public_tags=["city_walk", "industrial_heritage", "public_story"],
            geo={"status": "needs_geocoding", "place_candidates": ["黄浦江", "渡口", "桥梁"]},
        ),
        seed_record(
            record_id="demo-cemetery-memory-052",
            title="墓园、纪念册与人物关系复核",
            snippet="墓园记录、纪念册和讣告可帮助确认人物生卒、亲属关系和社会网络，但需要和人名规范、报刊、家谱等多源互证。",
            dataset="demo_seed:memorial_records",
            date="近代/民国",
            places=["上海"],
            topics=["墓园", "纪念册", "讣告", "生卒", "亲属关系", "人名规范"],
            source_uri=SHLIB_BOOK_URL,
            evidence_type="memorial_context_seed",
            public_tags=["family_memory", "trace_person", "source_verification"],
        ),
        seed_record(
            record_id="demo-dialect-place-name-053",
            title="方言地名、别称与口述线索消歧",
            snippet="方言地名和俗称常出现在口述史、家书和地方记忆中，需要和正式地名、道路改名、地图和报刊材料对应。",
            dataset="demo_seed:alias_place_names",
            date="近代/现代",
            places=["上海"],
            topics=["方言地名", "别称", "口述线索", "道路改名", "地图", "消歧"],
            evidence_type="alias_authority_seed",
            public_tags=["family_memory", "city_walk", "source_verification"],
            geo={"status": "needs_geocoding", "place_candidates": ["上海"]},
        ),
        seed_record(
            record_id="demo-community-curation-054",
            title="社区共创、线索征集与公共历史工作流",
            snippet="公众上传的姓名、旧地址、照片说明和问题可以进入线索池，再由系统生成检索计划、证据卡和待复核清单，可用于公开历史研究体验。",
            dataset="demo_seed:community_workflow",
            date="方法型记录",
            topics=["社区共创", "线索征集", "旧照片", "旧地址", "待复核清单", "公共历史"],
            evidence_type="method_context_seed",
            public_tags=["award_readiness", "public_story", "family_memory", "city_walk"],
        ),
    ]
)
